app:
  name: "golang_cli"
  mode: "dev"
  port: 8080

log:
  level: "DEBUG"
  filename: "./log/data.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "123456"
  db_name: "golang_cli"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "127.0.0.1"
  post: 16379
  password: ""
  db: 0
  pool_size: 100